config/routes.rb
LitePotosys::Application.routes.draw do
  devise_for :users
  root :to => 'home#homepage'

  resources :suppliers 
  
=begin
  CREATING MASTER DATA for resources 
=end
  resources :packages do 
    resources :package_assignments 
    resources :deliverable_subcriptions 
  end
  
  resources :deliverables do
    resources :deliverable_components
  end
  
 
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post


=begin
  MASTER DATA, company specific
  CREATE DELIVERABLE  + PACKAGE
=end
  match 'select_deliverable_to_create_component' => 'deliverables#select_deliverable_to_create_component', :as => :select_deliverable_to_create_component
  

  match 'create_package_assignment' => 'package_assignments#create_package_assignment', :as => :create_package_assignment, :method => :post 
  match 'edit_price_package/:package_id/crew/:crew_id' => 'package_assignments#edit_crew_specific_package_price', :as => :edit_crew_specific_package_price, :method => :post 

  match 'contact_person_info/:supplier_id' => 'suppliers#contact_person_info', :as => :contact_person_info

    
=begin
  INITIATE BACK OFFICE PROCESS : assign project Membership + PROJECT ROLE to employee
=end
  match 'select_project_for_project_membership_assignment' => 'projects#select_project_for_project_membership_assignment', :as => :select_project_for_project_membership_assignment
  match 'select_role_to_assign_employee/:project_id' => 'projects#select_role_to_assign_employee', :as => :select_role_to_assign_employee
  match 'assign_member_with_selected_project_role/:project_role_id/to_project/:project_id' => 'project_memberships#assign_member_with_selected_project_role_to_project', :as => :assign_member_with_selected_project_role_to_project

end

app/models/deliverable.rb
NumberValidator
class Deliverable < ActiveRecord::Base
  
  attr_accessible :name, :description, :sub_item_quantity, :independent_price, 
            :has_sub_quantity, :office_id, :has_sub_item, :sub_item_name, :independent_sub_item_price
  belongs_to :office
  
  has_many :packages, :through => :deliverable_subcriptions 
  has_many :deliverable_subcriptions 
  
  has_many :projects, :through => :deliverable_items
  has_many :deliverable_items # the subcription from project 
  
  has_many :deliverable_components 
  
  
  validates_presence_of :name 
  
  def set_office(office)
    self.office_id = office.id
    self.save 
  end
  
=begin
  Create Component needs to be monitored for production and post-production
=end

  def create_component(employee, component_params)
    if not employee.has_role?(:admin)
      return nil
    end
    
    component = DeliverableComponent.new 
    component.office_id = self.office_id 
    component.name = component_params[:name]
    component.deliverable_id = self.id 
    component.save 
    
    return component 
  end
  
  
  
  
  
end

app/controllers/deliverables_controller.rb
class DeliverablesController < ApplicationController
  def new
    @new_deliverable = Deliverable.new 
    
    @office = current_office 
  end
  
  def create
    @office = current_office
    
    @new_deliverable =  @office.create_deliverable( current_user, params[:deliverable])
    
    if  @new_deliverable.persisted?
      flash[:notice] = "The component '#{@new_deliverable.name}' has been created." 
      redirect_to new_deliverable_url 
      return 
    else
      flash[:error] = "Hey, do something better"
      
      render :file => "deliverables/new"
    end
  end
  
=begin
  CREATING THE COMPONENT for PRODUCTION + POST PRODUCTION monitoring 
=end
  
  def select_deliverable_to_create_component
    @deliverables = current_office.deliverables 
    add_breadcrumb "Search Deliverable", 'select_deliverable_to_create_component_url' 
  end

end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

app/views/deliverables/new.html.erb
<div class="span9 content">
  <%= create_guide("Create Deliverable", 
        "Office: <b>#{current_office.name}</b>"  ).html_safe %>
  
  <%#= create_breadcrumb(@breadcrumbs).html_safe %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Well done!</strong> <%= flash[:notice].html_safe %>
    </div>
  <% end %>
  
  <% if flash[:error] %>
    <div class="alert alert-error">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Create Failure!</strong> Please fill in all fields.
    </div>
  <% end %>
  
  
  <div class="row-fluid">
    <div class="span12">
      
      
      <!-- <button href="#" class="btn"></button> -->
      
      <%= link_to "Add New Deliverable", '#', :class => " btn btn-primary default-hidden-toggler"  %>
      <%= simple_form_for(@new_deliverable, :html => {:class => "form-horizontal prevent_double_submit form-toggler  #{add_default_hidden(params)}" }) do |f| %>
        
        
        <%#= f.input :machine_id, :hint => "Select Machine", :label => "Machine" do %>
           <%#= f.select :machine_id, 
               current_office.all_machines %>
         <%# end %>
         
         
        <%= f.input :name , :input_html => {:class => "input-xlarge span5"}, 
         :label => "Deliverable Name", :hint => "Canvas? Album?" %>
         
        <%= f.input :description , :input_html => {:rows => 5, :columns => 20, :class => "input-xlarge span5"}, 
          :label => "Description", :hint => "Details about this deliverable" %>
          
        <%= f.input :independent_price , :input_html => {:class => "input-xlarge span5"}, 
          :label => "Deliverable Price", :hint => "Independent Price, if it is counted as add-on" %>
          
        <%= f.input :has_sub_item , 
          :label => "Has Sub Item?", :hint => "If yes, check the box. " %>
          
        <%= f.input :sub_item_name , :input_html => {:class => "input-xlarge span5"}, 
          :label => "Sub Item Name", :hint => "CD with 40 edited image. Edited image is the sub item." %>

        <%= f.input :sub_item_quantity , :input_html => {:class => "input-xlarge span5"}, 
          :label => "Sub Item Quantity", :hint => "If there are sub items, such as: album with 50 edited photo." + 
                " Edited photo is the sub item. 50 is the quantity" %>
                
        <%= f.input :independent_sub_item_price , :input_html => {:class => "input-xlarge span5"}, 
          :label => "Additional Sub Item Price", :hint => "Independent Price, if it is counted as add-on" %>

        


        <div class="form-actions">
          <%= f.button :submit , :class => "btn btn-primary", :text=> "Create Component" %>
        </div>
      <% end %>
      
      
     
      
    </div> 
      
      
      
    
  </div><!--/row-->
   <hr />
  <div class="row-fluid">
    <div id="data_list">
      <h2>Total Deliverable for office  <%= @office.name %>: <%= @office.deliverables.count  %> </h2>
      
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Deliverable Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Sub Item Name</th>
            <th>Sub Item Quantity</th>
            <th>Extra Sub Item Price</th>
          </tr>
        </thead>
        <tbody>
          <% @office.deliverables.order("created_at DESC").each do |deliverable| %>
            <tr>
              <td><%= deliverable.name  %></td>
              <td><%= deliverable.description  %></td>
              <td><%= print_money( deliverable.independent_price )   %></td>
              
              <% if deliverable.has_sub_item == false %>
                <td colspan='3' style="text-align:center;"><span class="label">No Sub Item</span></td>
              <% else %>
              <td><%= deliverable.sub_item_name  %></td>
              <td><%= deliverable.sub_item_quantity  %></td>
              <td><%= print_money( deliverable.independent_sub_item_price )   %></td>
              <% end %>
              
              
            </tr>
          <% end %>

        </tbody>
      </table>
    </div><!-- end of #data_list -->
  </div>

</div><!--/span-->

app/views/deliverables/select_deliverable_to_create_component.html.erb
<div class="span9 content">
  <%= create_guide("Deliverable Component", 
        "Select deliverable  to <b>manage component</b>" + "<br />" + 
        "Office: <b>#{current_office.name}</b>"   ).html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Well done!</strong> <%= flash[:notice].html_safe %>
    </div>
  <% end %>
  
  <% if flash[:error] %>
    <div class="alert alert-error">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Create Failure!</strong> Please fill in all fields.
    </div>
  <% end %>
  
  
 
  <div class="row-fluid">
    <div id="data_list">
      
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Deliverable Name</th>
            <th>Description</th>
            <th>Component</th> 
          </tr>
        </thead>
        <tbody>
          <% @deliverables.each do |deliverable| %>
            <tr>
              <td><%= link_to deliverable.name , new_deliverable_deliverable_component_url(deliverable) %></td>
              <td><%= deliverable.description  %></td>
              <td><%= deliverable.deliverable_components.count   %></td>
             
              
            </tr>
          <% end %>

        </tbody>
      </table>
    </div><!-- end of #data_list -->
  </div>

</div><!--/span-->


 