config/routes.rb
LitePotosys::Application.routes.draw do
  devise_for :users
  root :to => 'home#homepage'

  resources :suppliers 
  
=begin
  CREATING MASTER DATA for resources 
=end
  resources :packages do 
    resources :package_assignments 
    resources :deliverable_subcriptions 
  end
  
  resources :deliverables do
    resources :deliverable_components
  end
  
 
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post


=begin
  MASTER DATA, company specific
  CREATE DELIVERABLE  + PACKAGE
=end
  match 'select_deliverable_to_create_component' => 'deliverables#select_deliverable_to_create_component', :as => :select_deliverable_to_create_component
  

  match 'create_package_assignment' => 'package_assignments#create_package_assignment', :as => :create_package_assignment, :method => :post 
  match 'edit_price_package/:package_id/crew/:crew_id' => 'package_assignments#edit_crew_specific_package_price', :as => :edit_crew_specific_package_price, :method => :post 

  match 'contact_person_info/:supplier_id' => 'suppliers#contact_person_info', :as => :contact_person_info

    
=begin
  INITIATE BACK OFFICE PROCESS : assign project Membership + PROJECT ROLE to employee
=end
  match 'select_project_for_project_membership_assignment' => 'projects#select_project_for_project_membership_assignment', :as => :select_project_for_project_membership_assignment
  match 'select_role_to_assign_employee/:project_id' => 'projects#select_role_to_assign_employee', :as => :select_role_to_assign_employee
  match 'assign_member_with_selected_project_role/:project_role_id/to_project/:project_id' => 'project_memberships#assign_member_with_selected_project_role_to_project', :as => :assign_member_with_selected_project_role_to_project

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :name
  has_many :users, :through => :job_attachments 
  has_many :job_attachments
  
  has_many :suppliers
  has_many :packages
  has_many :deliverables
  
=begin
  CREATING USER
=end
  def create_employee_by_email( employee, email, name  )
    user = User.create :email => email, 
      :name => name, 
      :password => 'willy1234', 
      :password_confirmation => 'willy1234'

    if not user.valid? 
      return user
    else
      JobAttachment.create(:office_id => self.id, :user_id => user.id)
      return user 
    end


  end

  def users
    User.joins(:job_attachments).where(
    :job_attachments => {
      :is_deleted => false,
      :office_id => self.id
    })
  end

  def main_user
    User.find_by_id self.main_user_id
  end

  def create_main_user(role_list, user_hash) 
    user = self.create_basic_user(role_list, user_hash)
    self.main_user_id = user.id 
    self.save
    return user 
  end
  
  def create_basic_user(role_list, user_hash)
    new_user = User.new(user_hash)

    if not new_user.save
      return new_user
    end

    job_attachment = JobAttachment.create(:user_id => new_user.id, :office_id => self.id)

    role_list.each do |role|
      Assignment.create_role_assignment_if_not_exists( role,  new_user)
    end

    return new_user
  end

  def create_user(employee, role_list, user_hash)
    if not employee.has_role?(:admin)
      return nil
    end
     #    
     # new_user = User.new(user_hash)
     # 
     # if not new_user.save
     #   return new_user
     # end
     # 
     # job_attachment = JobAttachment.create(:user_id => new_user.id, :office_id => self.id)
     # 
     # role_list.each do |role|
     #   Assignment.create_role_assignment_if_not_exists( role,  new_user)
     # end
 
    return self.create_basic_user(role_list, user_hash) 
  end
  
  
=begin
  MASTER DATA: Create Deliverable and Package
=end

  def create_deliverable( employee, deliverable_params)
    deliverable = Deliverable.new(deliverable_params)
    if not employee.has_role?(:admin)
      deliverable.errors.add(  :authentication , "Wrong Role: No admin role")
      return deliverable
    end



    if not ( deliverable_params[:has_sub_item].class == TrueClass or deliverable_params[:has_sub_item].class == FalseClass )
      if deliverable_params[:has_sub_item].to_i == TRUE_CHECK
        deliverable_params[:has_sub_item] = true
      else
        deliverable_params[:has_sub_item] = false
      end
    end

    # only validate the sub_item if it is declared as having sub item 
    if deliverable_params[:has_sub_item] == true 
      if not Deliverable.valid_price_string?(deliverable_params[:independent_price])
        deliverable.errors.add(  :independent_price , "Invalid Price")
      end

      if deliverable_params[:sub_item_name].nil? or deliverable_params[:sub_item_name].length == 0 
        deliverable.errors.add(  :sub_item_name , "Invalid Sub Item Name")
      end

      if  deliverable_params[:sub_item_quantity].nil? or 
          not Deliverable.is_numeric?( deliverable_params[:sub_item_quantity] ) or 
            deliverable_params[:sub_item_quantity].length == 0 
        deliverable.errors.add(  :sub_item_quantity , "Invalid Sub Item Quantity")
      end

       if not Deliverable.valid_price_string?(deliverable_params[:independent_sub_item_price])
          deliverable.errors.add(  :independent_sub_item_price , "Invalid Sub Item Price")
        end

      if deliverable.errors.messages.length != 0   
        return deliverable
      end
    end

    deliverable_params[:independent_price] = Deliverable.parse_price(deliverable_params[:independent_price] )  

    deliverable.update_attributes deliverable_params
    deliverable.office_id = self.id 
    deliverable.save 

    return deliverable 

    # check deliverable.persisted? 
    # check whether there is error 
    # result.errors.messages.length
  end

  def create_package( employee, package_params)
    package = Package.new(package_params)
    if not employee.has_role?(:admin)
      package.errors.add(  :authentication , "Wrong Role: No admin role")
      return package
    end

    #  cleaning up the boolean 
    if not ( package_params[:is_crew_specific_pricing].class == TrueClass or 
        package_params[:is_crew_specific_pricing].class == FalseClass  or 
        package_params[:is_crew_specific_pricing].nil?)
      if package_params[:is_crew_specific_pricing].to_i == TRUE_CHECK
        package_params[:is_crew_specific_pricing] = true
      else
        package_params[:is_crew_specific_pricing] = false
      end
    end

    package_params[:base_price] = Package.parse_price(package_params[:base_price] )  

    package.update_attributes package_params
    package.office_id = self.id 
    package.save


    return package 

  end

=begin
  Create Package's Deliverable
=end

  def all_deliverables
    deliverables  = self.deliverables.order("name ASC")
    result = []
    deliverables.each do |deliverable|
      if deliverable.has_sub_item == true 
        result << [ "#{deliverable.name} -- SubItem: #{deliverable.sub_item_name} "+
                "-- Default SubItem Quantity: #{deliverable.sub_item_quantity} "+
                "-- Additional Extra SubItem Price: #{deliverable.independent_sub_item_price}" , 
                        deliverable.id ]
      else
        result << [ "#{deliverable.name}" , 
                        deliverable.id ]
      end

    end
    return result
  end
  
=begin
  MASTER DATA: create supplier 
=end

  def create_supplier( employee, supplier_params) 
    supplier = Supplier.new(supplier_params)
    if not employee.has_role?(:admin)
      supplier.errors.add(  :authentication , "Wrong Role: No admin role")
      return supplier
    end



    supplier.office_id = self.id 
    supplier.creator_id = employee.id 
    supplier.save


    return supplier
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def new_employee_creation
    @new_employee = User.new 
    @employees = current_office.users
  end
  
  def create_employee
    @new_employee = current_office.create_user(current_user,  [], params[:user])
    
    if not @new_employee.nil? and @new_employee.valid?
      flash[:notice] = "The employee '#{@new_employee.email}' has been created." 
      redirect_to new_employee_creation_url
      return 
    else
      @employees = current_office.users
      flash[:error] = []
      if params[:user][:email].nil? or params[:user][:email].length == 0 
        flash[:error] << "Email has to be present"
      end
      
      if not User.find_by_email(params[:user][:email]).nil?
        flash[:error] << "There is duplicate email"
      end
        
      render :file => "offices/new_employee_creation"
    end
  end
  
  def show_role_for_employee
    @employee = User.find_by_id params[:employee_id]
    @roles = Role.find(:all, :order => "created_at DESC")
    
    add_breadcrumb "Select Employee", 'new_employee_creation_url'
    set_breadcrumb_for @employee, 'show_role_for_employee_url' + "(#{@employee.id})", 
                "Employee Role"
                
                
  end
  
  def assign_role_for_employee
    @decision = params[:membership_decision].to_i
    @role = Role.find_by_id params[:membership_provider]
    @employee = User.find_by_id params[:membership_consumer]
    @office = current_office
  
    if @decision == TRUE_CHECK
      puts "**** WE are calling add role "
      @employee.add_role(@role, @office, current_user)
    elsif @decision == FALSE_CHECK
      puts "((((( We are calling remove role)))))"
      @employee.remove_role(@role, @office,current_user)
    end
    
    respond_to do |format|
      format.html {  redirect_to root_url }
      format.js
    end
  end
  
  def test_crew_calendar
    @office = current_office
    @crews = current_office.crews 
  end
  
  def select_crew_to_view_calendar
    @office = current_office
    @crews = current_office.crews
    add_breadcrumb "Select Crew", select_crew_to_view_calendar_url
  end
  
  
  def show_all_bookings
    @crews = current_office.crews
    @job_requests_package = current_office.crew_booking_job_request_package
    add_breadcrumb "Current + Future Bookings", show_all_bookings_url
  end
  
=begin
  SALES&MArketing PENDING CONFIRMATIONS 
=end
  
  def pending_confirmation_sales_orders
    @sales_orders = current_office.pending_confirmation_sales_orders
    add_breadcrumb "Pending Confirmation", pending_confirmation_sales_orders_url
  end
  
  def confirmed_unfinalized_sales_orders
    @sales_orders = current_office.confirmed_unfinalized_sales_orders
    add_breadcrumb "Pending Confirmation", pending_confirmation_sales_orders_url
  end
=begin
  SALES AND MARKETING MANAGEMENT 
=end

  def select_employee_to_view_marketing_performance
    @marketers = current_office.marketers 
    @starting_date = ''
    @ending_date = ''
    today_date = Time.now.to_date
    
    if params[:starting_date].nil?  or params[:starting_date].length == 0 
      @starting_date = Date.new( today_date.year, today_date.month, 1 )
    else
      @starting_date = Project.extract_event_date(params[:starting_date])
    end
    
    if params[:ending_date].nil?  or params[:ending_date].length == 0 
      @ending_date = today_date
    else
      @ending_date = Project.extract_event_date(params[:ending_date])
    end
    
    add_breadcrumb "Overall Marketing Performance", select_employee_to_view_marketing_performance_url
    render :file => 'offices/marketing_management/select_employee_to_view_marketing_performance'
  end
  
  def marketing_performance_for
  end
  
  def customer_engagements
    # @marketers = current_office.marketers 
    @starting_date = ''
    @ending_date = ''
    today_date = Time.now.to_date
    
    if params[:starting_date].nil?  or params[:starting_date].length == 0 
      @starting_date = Date.new( today_date.year, today_date.month, 1 )
    else
      @starting_date = Project.extract_event_date(params[:starting_date])
    end
    
    if params[:ending_date].nil?  or params[:ending_date].length == 0 
      @ending_date = today_date
    else
      @ending_date = Project.extract_event_date(params[:ending_date])
    end
    
    @contact_reports = ContactReport.customer_engagements_between(current_office, @starting_date, @ending_date )
    
    add_breadcrumb "Customer Engagements", customer_engagements_url
    render :file => 'offices/marketing_management/customer_engagements'
  end
  
  def sales_summary
    @starting_date = ''
    @ending_date = ''
    today_date = Time.now.to_date
    
    if params[:starting_date].nil?  or params[:starting_date].length == 0 
      @starting_date = Date.new( today_date.year, today_date.month, 1 )
    else
      @starting_date = Project.extract_event_date(params[:starting_date])
    end
    
    if params[:ending_date].nil?  or params[:ending_date].length == 0 
      @ending_date = today_date
    else
      @ending_date = Project.extract_event_date(params[:ending_date])
    end
    
    @sales_orders = SalesOrder.sales_orders_between(current_office, @starting_date, @ending_date )
    
    add_breadcrumb "Customer Engagements", customer_engagements_url
    render :file => 'offices/marketing_management/sales_summary'
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
  def add_default_hidden_create_deadline_for_new_employee(params)
    if params[:action] != 'create_employee'
      return  'default-hidden'
    end
  end
   
end

 

app/views/offices/_employee_role_entry.html.erb
<tr>
  <td>
    <%= link_to employee.name , show_role_for_employee_url(employee) %>
  </td>
  <td>
    <% if employee.has_role?(:admin)%>
      <span class="label label-success">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td>
  
  
  <td>
    <% if employee.has_role?(:crew)%>
      <span class="label label-success">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td>
  
   
  
   
  
  <td>
    <% if not employee.has_role?(:project_manager_head) and not employee.has_role?(:project_manager)%>
      <span class="label">No</span>
    <% else %>
      <% if employee.has_role?(:project_manager_head)  %>
        <span class="label label-success">Head</span> 
      <% end %>
    
      <% if employee.has_role?(:project_manager) and not employee.has_role?(:project_manager_head)%>
        <span class="label label-success">Yes</span> 
      <% end %>
    <% end %>
  </td>
  
  <td>
    <% if not employee.has_role?(:production_head) and not employee.has_role?(:production)%>
      <span class="label">No</span>
    <% else %>
      <% if employee.has_role?(:production_head)  %>
        <span class="label label-success">Head</span> 
      <% end %>
    
      <% if employee.has_role?(:production) and not employee.has_role?(:production_head)%>
        <span class="label label-success">Yes</span> 
      <% end %>
    <% end %>
  </td>
  
  <td>
    <% if employee.has_role?(:account_executive)%>
      <span class="label label-success">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td>
  
  <td>
    <% if not employee.has_role?(:post_production_head) and not employee.has_role?(:post_production)%>
      <span class="label">No</span>
    <% else %>
      <% if employee.has_role?(:post_production_head)  %>
        <span class="label label-success">Head</span> 
      <% end %>
    
      <% if employee.has_role?(:post_production) and not employee.has_role?(:post_production_head)%>
        <span class="label label-success">Yes</span> 
      <% end %>
    <% end %>
  </td>
  
  
</tr>

app/views/offices/_role_entry.html.erb
<tr id="role_entry_<%= role.id %>">
  <td>
    <%= role.name %>
  </td>
  <td>
    <% checkbox_value = employee.has_role?(role.name.underscore.to_sym) %>

    <%= check_box_tag 'is_checked', get_checkbox_value(checkbox_value )   , 
        checkbox_value, :class => 'checkbox_tracker', 
        :id => "provider_#{role.id}-consumer_#{employee.id}" %> OK
  </td>
</tr>

app/views/offices/new_employee_creation.html.erb
<div class="span9 content">
  <%= create_guide("Create Employee", 
        "Office: <b>#{current_office.name}</b>" + "<br />"   +
        "Total Employee: <b>#{@employees.count}</b>" ).html_safe %>
  
  <%#= create_breadcrumb(@breadcrumbs).html_safe %>
 
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Well done!</strong> <%= flash[:notice].html_safe %>
    </div>
  <% end %>
  
  <% if flash[:error] %>
    <div class="alert alert-error">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Create Failure!</strong> Please fill in all fields.<br />
      <% flash[:error].each do |error| %>
        <%= error.html_safe %>
      <% end %>
      
    </div>
  <% end %>
  
  
  <div class="row-fluid">
    <div class="span12">
      <!-- <h2>New Employee</h2><br /> -->
      
      <%= link_to "Add New Employee", '#', :class => " btn btn-primary default-hidden-toggler"  %>

      <%= simple_form_for( @new_employee, :url => create_employee_url,
        :html => {:class => "form-horizontal prevent_double_submit form-toggler" + 
          " #{add_default_hidden_create_deadline_for_new_employee(params)}" }) do |f| %>


        <%= f.input :name , :input_html => {:class => "input-xlarge span5"}, 
        :label => "Name" %>
        
        
        <%= f.input :email , :input_html => {:class => "input-xlarge span5"}, 
        :label => "Email" %>
        
        
       
        

        <div class="form-actions">
          <%= f.button :submit , :class => "btn btn-primary", :text=> "Create Employee" %>
        </div>
      <% end %>
    </div> 
  </div><!--/row-->
  <hr />

  <div class="row-fluid">
    <div class="span12">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" >
        <thead>
          <tr>
            <th>Name</th>
            <th>Admin</th>
            <th>Crew</th> 
            <th>Account Executive</th>
            <th>Project Manager</th>
            <th>Production</th> 
            <th>Post Production</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <%= render :partial => "offices/employee_role_entry", :locals => {
              :employee => employee
            }%>
          <% end %>

        </tbody>
      </table>
    </div><!-- end of #data_list -->
  </div>

</div><!--/span-->








<div class="modal" id="myModal" style="display:none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
    <div id="modal_notification" style="display:none;">
    </div>
    <%= form_tag  root_url,  :method => :put, :id=> "edit_form", 
          :class => " edit_model", :style =>"display:none;"  do  %>
          
          
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th colspan="2" style="text-align:center;">Data</th></tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <b>Part Code</b>
            </td>
            <td>
              <div class="input-append">
                <input class="string  input-xlarge span5"
                  id="current_part_code" name="part_code" />
              </div>
              
            </td>
          </tr>
          
          <tr>
            <td>
              <b>Price</b>
            </td>
            <td>
              <div class="input-append">
                <input class="string optional input-xlarge span5"
                  id="current_price" name="price" />
              </div>
              
            </td>
          </tr>
          
          <tr>
            <td colspan="2" style="text-align:center;">
              <button href="#" class="btn btn-primary" id="pay_backlog_and_save_balance">
                Update Spare Part
              </button>
            </td>
          </tr>
        </tbody>
      </table>
      
      
     
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn modal-closer">Close</a>
    <!-- <a href="#" class="btn btn-primary">Save changes</a> -->
  </div>
</div>

app/views/offices/show_role_for_employee.html.erb
<div class="span9 content">
  <%= create_guide("Assign Role", 
        "Office: <b>#{current_office.name}</b>" + "<br />"   +
        "Employee Name: <b>#{@employee.name}</b>"  + "<br />" +
        "Employee Email: <b>#{@employee.email}</b>" ).html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
 
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Well done!</strong> <%= flash[:notice].html_safe %>
    </div>
  <% end %>
  
  <% if flash[:error] %>
    <div class="alert alert-error">
      <a data-dismiss="alert" class="close">×</a>
      <strong>Create Failure!</strong> Please fill in all fields.<br />
      <% flash[:error].each do |error| %>
        <%= error.html_safe %>
      <% end %>
      
    </div>
  <% end %>
  
 
  <div class="row-fluid">
    <div id="data_list">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Role</th>
            <th>Is Assigned?</th>
          </tr>
        </thead>
        <tbody>
          <% USER_ROLE.each do |key,value| %>
            <% role = Role.find_by_name value %>
            <%= render :partial => 'offices/role_entry', :locals => {
              :role => role, 
              :employee => @employee
            }%>
          <% end %>
          
        </tbody>
      </table>
    </div><!-- end of #data_list -->
  </div>

</div><!--/span-->



<!-- compatibilities_url -->

<div class=" hidden" id="checkbox_form_wrapper">
  <%= form_for Assignment.new, :url => assign_role_for_employee_url,  :method => :post   do |f| %>
    <%= hidden_field_tag 'membership_provider' , ''  %>
    <%= hidden_field_tag 'membership_consumer', '' %>
    <%= hidden_field_tag 'membership_decision', '' %>
  <% end %>
</div>